### ISSUE TITLE
Consider using KDL instead of TOML

### ISSUE THREAD

**Issue by sudoBash418** [club-eh/ctf-challenge-toolkit#8]
[KDL](https://kdl.dev/) is a document language (think XML) which may be a better alternative to the `challenge.toml` files we use right now.  
Challenges are essentially documents, and a couple of examples 

Splitting the description into a standalone Markdown file might also help a lot (whether we switch to KDL or stick with TOML).

---

Example challenge definition in TOML:
```toml
[meta]
id = "my-challenge"
name = "My Challenge"
author = "sudoBash418"
description = """
This is a simple demo challenge.  
Challenge descriptions support *Markdown*.

Here's a [link](https://example.com).
"""
flag = "flag{d3m0_fl4g}"
difficulty = "easy"
tags = ["Example", "Demonstration", "Not A Real Challenge"]

[[hints]]
# Short, single-line hint
content = "Here's the first hint."

[[hints]]
# Multi-line hint
content = """
Here's another hint.
This one has multiple lines.
"""

[files]
include = [
    "source/example.bin",
]
rm_prefixes = ["source/"]
make_archive = false
```

Example challenge definition in KDL:
```kdl
// note: this example uses "flattened" metadata, but using a "meta" node would work as well
id "my-challenge"
name "My Challenge"
author "sudoBash418"
description = r#"
This is a simple demo challenge.  
Challenge descriptions support *Markdown*.

Here's a [link](https://example.com).
"#
flag "flag{d3m0_fl4g}"
difficulty "easy"
tag "Example"
tag "Demonstration"
tag "Not A Real Challenge"

// Short, single-line hint
hint "Here's the first hint."
// Multi-line hint
hint r#"
Here's another hint.
This one has multiple lines.
"#

files archive=False {
    include "source/example.bin" rm_prefix=1  // note: this example uses per-include prefix stripping, not global prefix stripping
}
```
